#!/bin/bash

# Dotfiles Installation Script
# Supports macOS, Linux, WSL, and Git Bash

set -e  # Exit on error

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="${DOTFILES_DIR:-$SCRIPT_DIR}"
BACKUP_DIR="${BACKUP_DIR:-$HOME/dotfiles_backup_$(date +%Y%m%d_%H%M%S)}"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

detect_os() {
    if [[ "$OSTYPE" == darwin* ]]; then
        printf '%s\n' "macos"
    elif [[ "$OSTYPE" == linux-gnu* ]]; then
        if grep -qi microsoft /proc/version 2>/dev/null; then
            printf '%s\n' "wsl"
        else
            printf '%s\n' "linux"
        fi
    elif [[ "$OSTYPE" == msys* || "$OSTYPE" == mingw* || "$OSTYPE" == cygwin* ]]; then
        printf '%s\n' "gitbash"
    else
        printf '%s\n' "unknown"
    fi
}

OS="$(detect_os)"

echo -e "${BLUE}================================${NC}"
echo -e "${BLUE}  Dotfiles Installation${NC}"
echo -e "${BLUE}================================${NC}"
echo ""
echo -e "${GREEN}Repo:${NC} $DOTFILES_DIR"
echo -e "${GREEN}Detected:${NC} $OS"
echo ""

# Write a stub file that sources the real repo file.
# This works on all platforms without needing symlink privileges.
stub_file() {
    local src="$1"
    local dest="$2"

    # Back up destination if it exists and isn't already our stub
    if [ -e "$dest" ] && ! grep -q "Generated by dotfiles/install.sh" "$dest" 2>/dev/null; then
        mkdir -p "$BACKUP_DIR"
        echo -e "${YELLOW}  Backing up:${NC} $dest → $BACKUP_DIR/"
        mv "$dest" "$BACKUP_DIR/"
    fi

    # Write the stub
    printf '# Generated by dotfiles/install.sh — do not edit directly.\n# Edit %s instead.\nsource "%s"\n' "$src" "$src" > "$dest"
    echo -e "${GREEN}  ✓ Stubbed:${NC} $dest → source $src"
}

# Install common files (all platforms)
echo -e "${BLUE}Installing common dotfiles...${NC}"
stub_file "$DOTFILES_DIR/.bashrc" "$HOME/.bashrc"
stub_file "$DOTFILES_DIR/.bash_profile" "$HOME/.bash_profile"

# Note about .bashrc.local
echo ""
echo -e "${BLUE}================================${NC}"
echo -e "${GREEN}✓ Installation complete!${NC}"
echo -e "${BLUE}================================${NC}"
echo ""
echo -e "${YELLOW}💡 Tip:${NC} Create ${BLUE}~/.bashrc.local${NC} for private/machine-specific config"
echo "   (This file won't be committed to git)"
echo ""
echo -e "${YELLOW}Examples for ~/.bashrc.local:${NC}"
echo "   export GITHUB_TOKEN=\"your-token\""
echo "   alias work='cd /path/to/work/projects'"
echo "   export COMPANY_SPECIFIC_VAR=\"value\""
echo ""

if [ -d "$BACKUP_DIR" ]; then
    echo -e "${YELLOW}📦 Backups saved to:${NC} $BACKUP_DIR"
    echo ""
fi

echo -e "${GREEN}Next steps:${NC}"
echo "  1. Reload your shell: ${BLUE}source ~/.bash_profile${NC}"
echo "  2. Or just open a new terminal window"
echo "  3. Push to GitHub: ${BLUE}cd \"$DOTFILES_DIR\" && git push${NC}"
echo ""
